# Generated by Django 4.0.4 on 2022-05-11 21:25

import IT_blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItMainBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='title')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('about', models.CharField(max_length=20, verbose_name='about')),
                ('about_body', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('services', models.CharField(max_length=30, verbose_name='title')),
                ('services_body', models.TextField(verbose_name='body')),
                ('services_image1', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('services_image2', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('services_image3', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('services_image4', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('blog_title', models.CharField(max_length=15, verbose_name='blog')),
                ('blog_image1', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('blog_image2', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('blog_image3', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('blog_image4', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_title', models.CharField(max_length=15, verbose_name='partners')),
                ('partners_logo1', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo2', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo3', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo4', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo5', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo6', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo7', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo8', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo9', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo10', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo11', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo12', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo13', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo14', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo15', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo16', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo17', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo18', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo19', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo20', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo21', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
            ],
        ),
    ]
