# Generated by Django 4.0.4 on 2022-05-11 23:38

import IT_blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItAboutBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=20, verbose_name='about')),
                ('about_body', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ItBlogBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=15, verbose_name='blog')),
                ('blog_image1', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('blog_image2', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('blog_image3', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('blog_image4', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ItPartnersBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners_title', models.CharField(max_length=15, verbose_name='partners')),
                ('partners_logo1', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo2', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo3', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo4', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo5', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo6', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo7', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo8', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo9', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo10', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo11', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo12', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo13', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo14', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo15', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo16', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo17', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo18', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo19', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo20', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('partners_logo21', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ItServiceBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=30, verbose_name='title')),
                ('services_body', models.TextField(verbose_name='body')),
                ('services_image1', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('services_image2', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('services_image3', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
                ('services_image4', models.ImageField(blank=True, null=True, upload_to=IT_blogs.models.upload_location)),
            ],
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='about',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='about_body',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='blog_image1',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='blog_image2',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='blog_image3',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='blog_image4',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo1',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo10',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo11',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo12',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo13',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo14',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo15',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo16',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo17',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo18',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo19',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo2',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo20',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo21',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo3',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo4',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo5',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo6',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo7',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo8',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_logo9',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='partners_title',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='services',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='services_body',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='services_image1',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='services_image2',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='services_image3',
        ),
        migrations.RemoveField(
            model_name='itmainblogs',
            name='services_image4',
        ),
    ]
