# Generated by Django 4.0.4 on 2022-05-12 20:16

import IT_blogs.blogs.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0002_itaboutblogs_itblogblogs_itpartnersblogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('body_one', models.TextField(verbose_name='body_1')),
                ('body_two', models.TextField(verbose_name='body_2')),
                ('body_three', models.TextField(verbose_name='body_3')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=IT_blogs.blogs.service.upload_location)),
            ],
        ),
        migrations.DeleteModel(
            name='ItAboutBlogs',
        ),
        migrations.DeleteModel(
            name='ItBlogBlogs',
        ),
        migrations.DeleteModel(
            name='ItMainBlogs',
        ),
        migrations.DeleteModel(
            name='ItPartnersBlogs',
        ),
        migrations.DeleteModel(
            name='ItServiceBlogs',
        ),
    ]
