# Generated by Django 4.0.4 on 2022-05-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0003_headerservices_delete_itaboutblogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=20, verbose_name='services')),
                ('smm_title', models.CharField(max_length=20, verbose_name='blog_title')),
                ('comment', models.TextField(max_length=30, verbose_name='comment')),
                ('pages_smm', models.TextField(max_length=20, verbose_name='body')),
                ('post_smm', models.TextField(max_length=20, verbose_name='body')),
                ('photo_smm', models.TextField(max_length=20, verbose_name='body')),
                ('video_smm', models.TextField(max_length=20, verbose_name='body')),
                ('list_smm', models.TextField(max_length=20, verbose_name='body')),
            ],
        ),
    ]
