# Generated by Django 4.0.4 on 2022-05-13 01:13

import IT_blogs.blogs.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0004_mainservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=IT_blogs.blogs.service.upload_location),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='list_smm',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='pages_smm',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='photo_smm',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='post_smm',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='smm_title',
            field=models.CharField(max_length=30, verbose_name='blog_title'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='video_smm',
            field=models.TextField(verbose_name='body'),
        ),
    ]
