# Generated by Django 4.0.4 on 2022-05-13 02:53

import IT_blogs.blogs.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0005_mainservice_image_alter_mainservice_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smm_title', models.CharField(max_length=30, verbose_name='blog_title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('Android', models.TextField(verbose_name='body')),
                ('Automa', models.TextField(verbose_name='body')),
                ('Ios', models.TextField(verbose_name='body')),
                ('Google', models.TextField(verbose_name='body')),
                ('Appstore', models.TextField(verbose_name='body')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=IT_blogs.blogs.service.upload_location)),
            ],
        ),
    ]
