# Generated by Django 4.0.4 on 2022-05-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0006_mobileservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileservice',
            old_name='smm_title',
            new_name='phone_title',
        ),
    ]
