# Generated by Django 4.0.4 on 2022-05-13 03:22

import IT_blogs.blogs.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0007_rename_smm_title_mobileservice_phone_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStructureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_title', models.CharField(max_length=30, verbose_name='blog_title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('Online', models.TextField(verbose_name='body')),
                ('Landing', models.TextField(verbose_name='body')),
                ('Technical', models.TextField(verbose_name='body')),
                ('Corporate', models.TextField(verbose_name='body')),
                ('Complex', models.TextField(verbose_name='body')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=IT_blogs.blogs.service.upload_location)),
            ],
        ),
    ]
