# Generated by Django 4.0.4 on 2022-05-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0008_sitestructureservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItAboutModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('about', models.CharField(max_length=10000, verbose_name='about')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/%y')),
            ],
        ),
    ]
