# Generated by Django 4.0.4 on 2022-05-13 05:39

import IT_blogs.blogs.Partners
import IT_blogs.blogs.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0011_rename_smm_title_mainservice_blog_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location)),
            ],
        ),
        migrations.AlterField(
            model_name='headerservices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.service.upload_location),
        ),
    ]
