# Generated by Django 4.0.4 on 2022-05-13 05:47

import IT_blogs.blogs.Partners
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0012_partnersmodels_alter_headerservices_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnersmodels',
            old_name='image',
            new_name='logo_1',
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_10',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_11',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_12',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_13',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_14',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_15',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_16',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_17',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_18',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_19',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_2',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_20',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_3',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_4',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_5',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_6',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_7',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_8',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
        migrations.AddField(
            model_name='partnersmodels',
            name='logo_9',
            field=models.ImageField(blank=True, null=True, upload_to=IT_blogs.blogs.Partners.upload_location),
        ),
    ]
