# Generated by Django 3.2.13 on 2022-05-12 19:03

import IT_blogs.blogs.mainpage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_blogs', '0013_rename_image_partnersmodels_logo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPageBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('image1', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image1_title', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image2_title', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image3_title', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image4_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageHeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('title3', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image2', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image3', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageNumbersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('num1', models.IntegerField()),
                ('title1', models.CharField(max_length=50)),
                ('num2', models.IntegerField()),
                ('title2', models.CharField(max_length=50)),
                ('num3', models.IntegerField()),
                ('title3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('image1', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image1_title', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image2_title', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image3_title', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to=IT_blogs.blogs.mainpage.upload_location)),
                ('image4_title', models.CharField(max_length=50)),
            ],
        ),
    ]
